---
- name: Deleting environment OpenShift{{ ':' }} based on file openshift-definition.info
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - gce/authentication
     - gce/defaults
     - openshift-definition.info
     - notification/slack_authentication
  tasks:
     - include: commons/setting_defaults.yaml

     - name: "MASTER: Deleting instance exists: {{ master_definition.hostname }}"
       gce:
         instance_names: "{{  master_definition.hostname }}"
         zone: "{{ zone }}"
         state: "absent"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "MASTER: Deleting boot disk: {{ master_definition.hostname }}"
       gce_pd:
         name: "{{ master_definition.hostname }}"
         state: absent
         zone: "{{ zone }}"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "MASTER: Deleting a Static IP Address"
       gce_eip:
         name: "{{ master_definition.hostname }}"
         region: "{{ region }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "MASTER: Deleting Docker Storage: {{  master_definition.hostname }}-docker"
       gce_pd:
         name: "{{  master_definition.hostname }}-docker"
         zone: "{{ zone }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "INFRA: Deleting instance exists{{ ':' }} {{ infra_definition.hostname }}"
       gce:
         instance_names: "{{ infra_definition.hostname }}"
         zone: "{{ zone }}"
         state: "absent"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "INFRA: Deleting boot disk: {{ infra_definition.hostname }}"
       gce_pd:
         name: "{{ infra_definition.hostname }}"
         state: absent
         zone: "{{ zone }}"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "INFRA: Deleting a Static IP Address"
       gce_eip:
         name: "{{ infra_definition.hostname }}"
         region: "{{ region }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "INFRA: Deleting Docker Storage for: {{ infra_definition.hostname }}-docker"
       gce_pd:
         name: "{{ infra_definition.hostname }}-docker"
         zone: "{{ zone }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True

     - name: "NODE: Deleting ALL Nodes instances"
       gce:
         instance_names: "{{ item.hostname }}"
         zone: "{{ zone }}"
         state: "absent"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True
       with_items: "{{ nodes_definition }}"

     - name: "NODE: Deleting boot disk: {{ item.hostname }}"
       gce_pd:
         name: "{{ item.hostname }}"
         state: absent
         zone: "{{ zone }}"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       with_items: "{{ nodes_definition }}"
       ignore_errors: True

     - name: "NODE: Deleting ALL Nodes's docker storage"
       gce_pd:
         name: "{{ item.hostname }}-docker"
         zone: "{{ zone }}"
         state: absent
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True
       with_items: "{{ nodes_definition }}"

     - name: Notifying by Slack about sucessfully deletion
       slack: token={{ default_slack_token }} msg="OpenShift was successfully uninstalled"
       when: default_slack_token is defined and default_slack_token is not none
