- name: "Check Parameter: gce_credentials_file"
  fail: msg="gce_credentials_file is not defined or is empty"
  when: gce_credentials_file is not defined or gce_credentials_file is none
  tags: [ gce, ocp, initial, parameter ]

- name: "Check Parameter: gce_project_id"
  fail: msg="gce_project_id is not defined or is empty"
  when: gce_project_id is not defined or gce_project_id is none
  tags: [ gce, ocp, initial, parameter ]
  
- name: "Check Parameter: gce_service_account_email"
  fail: msg="gce_service_account_email is not defined or is empty"
  when: gce_service_account_email is not defined or gce_service_account_email is none
  tags: [ gce, ocp, initial, parameter ]
