- name: "Deleting ALL OpenShift: {{ name }}"
  azure_rm_resourcegroup: name={{ name }} state=absent force=True
                          subscription_id={{ azure_subscription_id }} tenant={{ azure_tenant }}
                          client_id={{ azure_client_id }} secret={{ azure_secret }}
  tags: [ ocp, azure, delete_all ]
