- name: "BASTION: Fetching Information"
  gce: instance_names={{ bastion_definition.hostname }} zone={{ gce_zone }}
       credentials_file={{ gce_credentials_file }}
       project_id={{ gce_project_id }} service_account_email={{ gce_service_account_email }}
  register: bastion_instance
  tags: [ ocp, gce, fetch, bastion ]

- name: "BASTION: Adding group: openshift_bastion"
  add_host: hostname={{ bastion_instance.instance_data[0].public_ip }}
            groups=openshift_bastion
            ansible_user={{ admin_username }}  ansible_password={{ gce_base_image_password }}
            bastion_public_ip={{ bastion_instance.instance_data[0].public_ip }}
  tags: [ ocp, gce, fetch, bastion ]
