- name: STARTING Bastion
  gce: instance_names="{{ bastion_definition.hostname }}" state=started zone={{ gce_zone }}
       project_id={{ gce_project_id }} credentials_file={{ gce_credentials_file }} 
       service_account_email={{ gce_service_account_email }}
  tags: [ ocp, start ]

- name: STARTING OpenShift Cluster
  gce: instance_names="{{ item.hostname }}" state=started zone={{ gce_zone }}
       project_id={{ gce_project_id }} credentials_file={{ gce_credentials_file }} 
       service_account_email={{ gce_service_account_email }}
  with_items: "{{ master_definition }}+{{ infra_definition }}+{{ node_definition }}"
  tags: [ ocp, start ]

- name: Fetching Bastion information
  gce: instance_names="{{ bastion_definition.hostname }}" zone={{ gce_zone }}
       project_id={{ gce_project_id }} credentials_file={{ gce_credentials_file }} 
       service_account_email={{ gce_service_account_email }}
  register: bastion_information
  tags: [ ocp, start ]

- name: Fetching Bastion Public IP
  set_fact: bastion_public_ip={{ bastion_information.instance_data[0].public_ip }}
  tags: [ ocp, start ]

- name: "LOCAL: Generating script to easy SSH Bastion"
  local_action: template src=ssh_bastion.sh.j2 dest=ssh_bastion.sh mode=a+x force=True
  when: bastion_public_ip is defined and bastion_public_ip is not none
  tags: [ ocp, start ]
